### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by JessamyT**

### CODE REVIEW

**Comment by hawkeyexl** [comment]
Thanks for the fix, @JessamyT! Once you agree to the [CLA](https://cla-assistant.io/doc-detective/doc-detective.github.io?pullRequest=54) (essentially saying that you agree to have your code under our MIT license), then I can merge it.

**Comment by JessamyT** [comment]
Oops done!

**Comment by hawkeyexl** [comment]
Merged!

**Comment by JessamyT** [comment]
Thank you for accepting my minuscule contribution :D

**Pull request merged**
